blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    # ex: /polls
    url(r'^$', views.archive, name='archive'),
    # ex: /polls/5/
    url(r'^(?P<article_id>[0-9]+)/$', views.blogpost, name='blogpost'),
]

podcast/urls.py
from django.conf.urls import url

from . import views

app_name = 'podcast'
urlpatterns = [
    url(r'^$', views.podcast_index, name='podcast_index'),
    url(r'^(?P<podcast_id>[0-9]+)/$', views.podcast_detail, name='podcast_detail')
]

home/views.py
from django.shortcuts import render, get_object_or_404
from django.template import RequestContext
from polls.models import Question, Choice
from blog.models import Article, Category
from podcast.models import Podcast
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
import datetime
from django.shortcuts import render_to_response
from itertools import chain
import operator
from django.db.models import Q
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.contrib.auth.models import User


def home(request):
    latest_question_list = Question.objects.order_by('-created')[:2]
    top_article = Article.objects.order_by('-pub_date')[:1]
    article_list = Article.objects.order_by('-pub_date')[1:5]
    podcast_list = Podcast.objects.order_by('-pub_date')[:3]
    now = datetime.datetime.now()
    context = {
        'latest_question_list':latest_question_list,
        'article_list':article_list,
        'top_article':top_article,
        'podcast_list':podcast_list,
        'now':now
    }
    return render(request, 'home/home.html', context)

def search(request):
    query = request.GET.get("q")

    article_queryset_list = Article.objects.all() 

    podcast_queryset_list = Podcast.objects.all()

    if  query:
        article_queryset_list = article_queryset_list.filter(
            Q(content__icontains=query) |
            Q(title__icontains=query)
        ).distinct()
        podcast_queryset_list = podcast_queryset_list.filter(
            Q(name__icontains=query)
        ).distinct()

    context = {
        "article_search_results":article_queryset_list,
        "podcast_search_results":podcast_queryset_list
    }
    return render(request, 'home/search_results.html', context)

home/templates/home/about.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        {% include "home/head.html" %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    </head>
    <body>
        <div class="background-image-moon full-height-viewport">
            <div class="col-sm-12">
                <div class="col-sm-3">
                    <p>
                        Thought Cosmonaut is a fully independent content platform dedicated to 
                    </p>
                </div>
                <div class="col-sm-3">
                    
                </div>
                <div class="col-sm-3">
                    
                </div>
                <div class="col-sm-3">
                    
                </div>
            </div>
        </div>
    </body>
</html>

home/templates/home/carousel.html
{% load static %}

<div id="homeCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#homeCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#homeCarousel" data-slide-to="1"></li>
        <li data-target="#homeCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active">
        <img src="{% static 'images/controller.jpg' %}">
        </div>

        <div class="item">
        <img src="{% static 'images/game.jpg' %}">
        </div>

        <div class="item">
        <img src="{% static 'images/video.jpg' %}">
        </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#homeCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#homeCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<script>
        // Activate Carousel
        $('#homeCarousel').carousel({
        interval: 2000
        })

        // Enable Carousel Indicators
        $(".item").click(function(){
            $("#homeCarousel").carousel(1);
        });

        // Enable Carousel Controls
        $(".left").click(function(){
            $("#homeCarousel").carousel("prev");
        });

    </script>

home/templates/home/footer.html
{% load static %}

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    {% include 'home/head.html' %}
</head>

<div class="container-fluid">
    <div class="row">
                <div class="col-sm-4">
                    <a href="https://www.patreon.com/thoughtcosmonaut" class="title-font color-white">Support Us</a>
                </div>
                <div class="col-sm-4 color-white">
                    <p class="title-font">Thought Cosmonaut   |   {{ now }}</p>
                </div>
                <div class="col-sm-4">
                    <a href="https://github.com/npeters52/thought-cosmonaut" class="title-font color-white">GitHub</a>
                </div>
        </div>
</div>

home/templates/home/head.html
{% load static %}

<title>Thought Cosmonaut</title>  
<link rel="icon" type="image/x-icon" href="/MEDIA/dark_logo.jpg" />
<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
<!-- jquery -->
<script src="//code.jquery.com/jquery.js"></script>         
<!-- font-awesome -->
<script src="https://use.fontawesome.com/6d1f38039d.js"></script>
<!-- fonts -->
<link href="https://fonts.googleapis.com/css?family=Bungee+Inline" rel="stylesheet">
<!-- bootstrap -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1">

home/templates/home/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        {% include "home/head.html" %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    </head>
    <body class="full-page">
        <div class="full-width">
            {% include "home/nav.html" %}
        </div>
        <div class="container-fluid background-image-night full-page">
            <div class="col-sm-12 home-splash">
                <div class="row">
                    <div class="col-sm-12 home-main">
                        {% include 'blog/blog_index.html' %}
                    </div>
                </div>
            </div>
        </div>
        <div class="podcast-home text-center background-image-mountains full-page">
            <div class="col-sm-12">
                    {% include 'podcast/podcast_home_splash.html' %}
            </div>
            <div class="row footer-bottom">
                <div class="col-sm-12 text-center">
                    {% include 'home/footer.html' %}
                </div>
            </div>
        </div>
    </body>
</html>

home/templates/home/nav.html
{% load static %}
{% load search %}
<head>
        <link rel="stylesheet" type="text/css" href="{% static 'css/nav-style.css' %}"/>
</head>
<!--<img src="/MEDIA/logo.png">-->
<div class="topnav" id="myTopnav">
        <a class="title-font title" href="{% url 'home' %}">Thought Cosmonaut</a>
        <a class="title-font nav-li nav-a" href="https://twitter.com/cosmo_thought">Stream of Thought</a>
        <a class="title-font nav-li nav-a" href="/podcast">Podcast</a>
        <a class="title-font nav-li nav-a" href="/blog">Blog</a>
        <!--search-->
        <div class="title-font nav-li search-base search-container color-black" id="search">
          <form action="/search" method="GET">
            <input type="text" class="form-control" name="q" placeholder="Search..." name="search" value='{{ request.GET.q }}'>
          </form>
        </div>
        <a href="javascript:void(0);" class="icon" onclick="navResponsive()">
            <i class="fa fa-bars"></i>
        </a>
        <a href="javascript:void(0);" class="search-icon" id="searchIcon" onclick="searchResponsive()">
          <i id="searchImage" class="glyphicon glyphicon-search"></i>
        </a>
</div>


<script>
  /* Toggle between adding and removing the "responsive" class to topnav when the user clicks on the icon */
  function navResponsive() {
    var x = document.getElementById("myTopnav");
    var y = document.getElementById("search");
    var w = document.getElementById("searchIcon");
    if (x.className === "topnav") {
        x.className += " responsive";
        w.className += " responsive";
    } else {
        x.className = "topnav";
        y.className = "search-container";
        w.className = "search-icon";
    }
  } 

  function searchResponsive() {
    var y = document.getElementById("search");
    var z = document.getElementById("searchImage")
    if (y.className === "search-base") {
      y.className += " search-container";
    } else {
      y.className = "search-base";
    }
    if (z.className === "glyphicon glyphicon-search") {
      z.className = "glyphicon glyphicon-remove";
    } else {
      z.className = "glyphicon glyphicon-search"
    }
  }
</script>

home/templates/home/search_results.html
{% load staticfiles %}

<head>
    {% include "home/head.html" %}
    <link rel="stylesheet" type='text/css' href="{% static 'css/blog.css' %}">
</head>

<body class="theme-white">
    <div class="container-fluid theme-white">
        <div class="col-sm-12 theme-white padding-bottom">
            <div>
                {% include "home/nav.html" %}
            </div>
            <div class="archive-splash">
                <h1 class="color-black text-center title-font blog-title">Search Results</h1>
                {% if article_search_results %}
                <div>
                    <ul class="blog-ul text-center">
                        {% for article in article_search_results %}
                        <div  class="row theme-white">
                            <li>
                                <h1>
                                    <a class="color-black title-font top-article-title" style="text-decoration:none" href="{% url 'blog:blogpost' article.id %}">{{ article.title }}</a>
                                </h1>
                                <h4>
                                    <p class="color-black title-font">
                                        {{result.pub_date}}
                                    </p>
                                </h4>
                            </li>
                        </div>
                        {% endfor %}
                    </ul>
                </div>
                {% else %}
                <p class="color-black text-center"> No articles found </p>
                {% endif %}
                {% if podcast_search_results %}
                    <ul class="podcast-block img-responsive theme-white">
                        {% for podcast in podcast_search_results %}
                        <div  class="row col-sm-12 podcast-block center theme-white">
                            <li>
                              <h1 class="text-center">
                                <a class="color-black title-font top-article-title" style="text-decoration:none" href="{% url 'podcast:podcast_detail' podcast.id %}">{{ podcast.name }}</a>
                              </h1>
                              <h4 class="text-center">
                                  <p class="color-black title-font">
                                      {{podcast.pub_date}}
                                  </p>
                              </h4>
                            </li>
                        </div>
                        {% endfor %}
                    </ul>
                    {% else %}
                        <p class="color-black text-center">No podcasts found</p>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="row text-center theme-white blog-archive-footer">
        {% include "home/footer.html" %}
    </div>
</body>