blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    # ex: /polls
    url(r'^$', views.archive, name='archive'),
    # ex: /polls/5/
    url(r'^(?P<article_id>[0-9]+)/$', views.blogpost, name='blogpost'),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

polls/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import datetime

# Create your models here.
class Question(models.Model):
    """
    data fields for the questions
    """
    question_text = models.CharField(max_length=200)
    created = models.DateTimeField('date published')
    is_active = models.BooleanField(default=True)
    author = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)

    def was_published_recently(self):
        """
        method for returning questions posted within the last day
        """
        return self.created >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    """
    data fields for the choices
    """
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text
    

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice
from django.template import loader
from django.urls import reverse

# Create your views here.

def index(request):
    latest_question_list = Question.objects.order_by('-created')[:5]
    context = {
        'latest_question_list':latest_question_list
    }
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question':question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/detail.html
{% load static %}

<head>
    {% include "home/head.html" %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/poll-style.css' %}"/>
</head>
<body>
    {% include "home/nav.html" %}
    <div class="row col-sm-12 poll-splash text-center theme-green">
        <h1> {{question.question_text}} </h1>
        <div class="row col-sm-12">
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                <form action="{% url 'polls:vote' question.id %}" method="post">
                {% csrf_token %}
                {% for choice in question.choice_set.all %}
                        <input class="choice-button btn btn-warning" type="checkbox" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
                        <label class="choice" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
                {% endfor %}
                <input class="btn btn-primary submit" type="submit" value="Vote" />
                </form>
        </div>
    </div>
</body>

polls/templates/polls/index.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'css/poll-style.css' %}"/>
    </head>
    <body>
        <div class="col-sm-12 poll-splash">
            {% if latest_question_list %}
            <div class=" poll_list">
                <ul class="question-ul">
                    {% for question in latest_question_list %}
                    <div  class="col-sm-4 question-block text-center">
                        <li>
                            <a class="theme-green clickable" style="text-decoration:none" href="{% url 'polls:detail' question.id %}">{{ question.question_text }} </a>
                        </li>
                    </div>
                    {% endfor %}
                </ul>
                {% else %}
                    <p class="theme-green"> No polls are available </p>
            </div>
            {% endif %}
        </div>
    </body>
</html>

polls/templates/polls/results.html
{% load static %}

<head>
    {% include "home/head.html" %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/poll-style.css' %}"/>
</head>
<body>
    <div>
        {% include "home/nav.html" %}
    </div>
    <div class="row">
        <div class="col-sm-12 poll-splash text-center theme-green">
            <h1>{{ question.question_text }}</h1>
            <ul>
            {% for choice in question.choice_set.all %}
                <li class="result-li">{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
            {% endfor %}
            </ul>
            <div class="row back-button">
                <a class="btn btn-primary" href="{% url 'home' %}">Home</a>
            </div>
        </div>
    </div>
</body>